name: Generate lockfile

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Remove old lockfiles
        run: rm -f package-lock.json pnpm-lock.yaml yarn.lock

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Commit lockfile
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add package-lock.json
          git commit -m "generate full package-lock.json"
          git push
